
jwt:
  signing-key: qmPlus
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus

zap:
  level: info
  format: console
  prefix: "[jili/server]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""

email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test

system:
  env: local
  addr: 8888
  db-type: mysql
  oss-type: local
  use-redis: false
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
  router-prefix: ""


captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0
  open-captcha-timeout: 3600

mysql:
  path: "10.10.201.45"
  port: "3306"
  config: "charset=utf&parseTime=True&loc=Local" # 含义？
  db-name: "jili_gin_vue_admin_main_test"
  username: "jili"
  password: "jili_gin_vue_admin_main_test"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

local:
  path: uploads/file
  store-path: uploads/file

autocode:
  transfer-restart: true
  root: ""
  server: /server
  server-plug: /plugin/%s
  server-api: /api/v1/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-request: /model/%s/request/
  server-router: /router/%s
  server-service: /service/%s
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view

qiniu:
  zone: ZoneHuaDong
  bucket: ""
  img-path: ""
  use-https: false
  access-key: ""
  secret-key: ""
  use-cdn-domains: false

excel:
  dir: ./resource/excel/

Timer:
  start: true
  spec: "@daily"
  detail:
    - tableName: sys_operation_records
      compareField: created_at
      interval: 2160h
    - tableNmae: jwt_blacklists
      compareField: created_at
      interval: 168h

cors:
  mode: strict-whitelist
  whitelist:
    - allow-origin: example1.com
      allow-headers: Content-Type, AccessToken, X-CSRF-Token, Authorization, Token, X-Token, X-User-Id
      allow-methods: POST, GET
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true
    - allow-origin: example2.com
      allow-headers: content-type
      allow-methods: GET, POST
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true